name: mini-dropbox

dependencies:
  - base
  - warp
  - aeson
  - servant-elm
  - servant
  - wai
  - transformers
  - containers
  - heist
  - map-syntax
  - snap
  - snap-server
  - servant-snap
  - xmlhtml
  - snap-cors
  - snaplet-postgresql-simple
  - postgresql-simple
  - snap-core
  - lens
  - mtl
  - text
  - time 
  - elm-export
  - unordered-containers

executables:
  mini-dropbox:
    main: Main.hs
    source-dirs:
      - server/src

  generate:
    main: GenerateElm.hs
    source-dirs:
      - server/src
      - client
