name: mini-dropbox

dependencies:
  - base
  - warp
  - aeson
  - servant-elm
  - servant
  - wai
  - transformers
  - containers
  - heist
  - map-syntax
  - snap
  - snap-server
  - servant-snap
  - xmlhtml
  - snap-cors
  - snaplet-postgresql-simple
  - postgresql-simple
  - snap-core
  - lens
  - mtl
  - text

executables:
  mini-dropbox:
    main: Main.hs
    source-dirs:
      - server/src
